languageCode = "en-gb"
title = "Harwell Software Community"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Harwell Software Community"
    description = '''\
      The initiative of the Harwell Software Community is "To build a community of software engineers on campus to network, share ideas, tools and techniques".\
      \
      We hold regular events ranging from talks, networking and workshops for those involved in software engineering throughout the Harwell campus.\
      \
      To keep up to date either join out [mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=HARWELL-SW-COMMUNITY) or [Slack community](https://harwell-sw-community.slack.com/).\
    '''
    profilePic = "images/banner.png"
    githubUsername = "harwellsoftwarecommunity"
    css = ["css/intro.css"]
    accent = "#1762a5"
    showBorder = true
    backgroundColor = "white"
    font = "Titillium Web" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/event/"
    name = "Events"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/harwellsoftwarecommunity/"
    name = "github"
    weight = 2
